services:
  - type: web
    name: sharebite-backend
    env: python
    region: oregon
    plan: free
    rootDir: sharebite_backend
    buildCommand: "./build.sh"
    startCommand: "gunicorn sharebite.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: sharebite-db
          property: connectionString

databases:
  - name: sharebite-db
    databaseName: sharebite
    user: sharebite
    plan: free
